name = "DirectQhull"
uuid = "c3f9d41a-afcb-471e-bc58-0b8d83bd86f4"
authors = ["Juha Heiskala <juha.t.heiskala@iki.fi>"]
version = "0.2.1"

[deps]
Qhull_jll = "784f63db-0788-585a-bace-daefebcd302b"

[compat]
Qhull_jll = "8.0.1001"
julia = "1.6"
